apiVersion: v1
baseDomain: {{ base_domain }}
metadata:
  name: {{ cluster_name }}
networking:
  machineNetwork:
  - cidr: {{ baremetal_net.net }}/{{ baremetal_net.prefix }}
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: {{ worker_nodes | list | length }}
controlPlane:
  name: master
  replicas: {{ master_nodes | list | length }}
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: {{ vip.api }}
    ingressVIP: {{ vip.apps }}
    bootstrapOSImage: BOOTSTRAPOSIMAGE
{% if redfish.enable == True  %}
    provisioningNetwork: Disabled
{% else %}
    provisioningNetworkCIDR: {{ provision_net.net }}/{{ provision_net.prefix }}
    provisioningNetworkInterface: {{ provision_net.net_interface }}
    provisioningBridge: "provisioning"
    provisioningDHCPRange: {{ provision_net.dhcp_start }},{{ provision_net.dhcp_end }}
    provisioningNetwork: Managed
{% endif %}
{% if cluster_dhcp_enabled == False %}
    bootstrapExternalStaticIP: {{ bootstrap_node.static_ip }}
    bootstrapExternalStaticGateway: {{ baremetal_net.gateway }}
    bootstrapExternalStaticDNS: {{ utility_nodes[0].baremetal_ip }}
{% endif %}
    externalBridge: "baremetal"
    hosts:
{% for host in master_nodes %}
{% if host != 'localhost' %}
      - name: {{ host.name }}
        role: master
        bmc:
{% if redfish.enable == True  %}
          address: redfish-virtualmedia://{{ host.redfish_ip }}:{{ host.redfish_port }}/redfish/v1/Systems/{{ host.name }}
          disableCertificateVerification: True
{% else %}
          address: ipmi://{{ host.vbmc_ip }}:{{ host.vbmc_port }}
{% endif %}
          username: admin
          password: {{ secure_password }}
{% if redfish.enable == True  %}
        bootMACAddress: {{ host.baremetal_mac }}
{% else %}
        bootMACAddress: {{ host.provisioning_mac }}
{% endif %}
        rootDeviceHints:
         deviceName: "/dev/vda"
{% if cluster_dhcp_enabled == False %}
        networkConfig:
          interfaces:
          - name: enp1s0
            type: ethernet 
            state: up 
            mac-address: {{ host.baremetal_mac }}
            permanent-mac-address: {{ host.baremetal_mac }}
            ipv4:
              enabled: false 
            ipv6:
              enabled: false
            controller: br-ex
          - name: br-ex
            type: ovs-bridge
            state: up
            ipv4:
              enabled: true
            ipv6:
              enabled: false
            bridge:
              port:
              - name: enp1s0
              - name: br-ex
          - name: br-ex
            type: ovs-interface
            state: up
            copy-mac-from: enp1s0
            ipv4:
              enabled: true
              dhcp: false
              address:
              - ip: {{ host.baremetal_ip }}
                prefix-length: {{ baremetal_net.prefix }}
            ipv6:
              enabled: false
          dns-resolver:
            config:
              server:
              - {{ utility_nodes[0].baremetal_ip }}
              search:
              - {{ domain }}
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: {{ baremetal_net.gateway }}
              next-hop-interface: br-ex
{% endif %}
        bootMode: legacy
{% endif %}
{% endfor %}
{% for host in worker_nodes %}
{% if host != 'localhost' %}
      - name: {{ host.name }}
        role: worker
        bmc:
{% if redfish.enable == True  %}
          address: redfish-virtualmedia://{{ host.redfish_ip }}:{{ host.redfish_port }}/redfish/v1/Systems/{{ host.name }}
          disableCertificateVerification: True
{% else %}
          address: ipmi://{{ host.vbmc_ip }}:{{ host.vbmc_port }}
{% endif %}
          username: admin
          password: {{ secure_password }}
{% if redfish.enable == True  %}
        bootMACAddress: {{ host.baremetal_mac }}
{% else %}
        bootMACAddress: {{ host.provisioning_mac }}
{% endif %}
        rootDeviceHints:
         deviceName: "/dev/vda"
 {% if cluster_dhcp_enabled == False %}
        networkConfig:
          interfaces:
          - name: eth0
            type: ethernet 
            mac-address: {{ host.baremetal_mac }}
            permanent-mac-address: {{ host.baremetal_mac }}
            state: up 
            ipv4:
              enabled: true
              dhcp: false
              address:
              - ip: {{ host.baremetal_ip }}
                prefix-length: {{ baremetal_net.prefix }}
            ipv6:
              enabled: false
              dhcp: false
          dns-resolver:
            config:
              server:
              - {{ utility_nodes[0].baremetal_ip }}
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: {{ baremetal_net.gateway }}
              next-hop-interface: eth0
{% endif %}
        bootMode: legacy
{% endif %}
{% endfor %}
